### ISSUE TITLE
"株式会社" should be splitted.

### ISSUE THREAD

**Issue by ghost** [neologd/mecab-ipadic-neologd#10]
I think these characters should be splitted:
（株）, (株), 株式会社

neologd has 5 "あおい電子工業" variants. 
- あおい電子工業 株式会社,1292,1292,-14635,名詞,固有名詞,組織,_,_,*,あおい電子工業株式会社,アオイデンシコウギョウカブシキガイシャ,アオイデンシコーギョーカブシキガイシャ
- あおい電子工業 （株）,1292,1292,-10826,名詞,固有名詞,組織,_,_,*,あおい電子工業株式会社,アオイデンシコウギョウカブシキガイシャ,アオイデンシコーギョーカブシキガイシャ
- あおい電子工業(株),1292,1292,6301,名詞,固有名詞,組織,_,_,*,あおい電子工業株式会社,アオイデンシコウギョウカブシキガイシャ,アオイデンシコーギョーカブシキガイシャ
- あおい電子工業株式会社,1292,1292,-9787,名詞,固有名詞,組織,_,_,*,あおい電子工業株式会社,アオイデンシコウギョウカブシキガイシャ,アオイデンシコーギョーカブシキガイシャ
- あおい電子工業（株）,1292,1292,-6382,名詞,固有名詞,組織,_,_,*,あおい電子工業株式会社,アオイデンシコウギョウカブシキガイシャ,アオイデンシコーギョーカブシキガイシャ

I don't think we need 5 variants for "あおい電子工業",
and, more importantly, neologd doesn't have basic "あおい電子工業 アオイデンシコウギョウ".

I think these entries are enough and we can reduce the dictionary size.
あおい電子工業 アオイデンシコウギョウ
株式会社 カブシキガイシャ
(株) カブシキガイシャ
（株） カブシキガイシャ

Regards.

**Comment by priancho** [comment]
Hi gary,

I think that the author will answer your question, but I would like to mention a few things on this issue :-)

The task normalizing lexical variants of the same named entity (entity normalization) usually belongs to a different stage in natural language processing since it is a very difficult problem as much as named entity recognition.

There are several problems involved. 
For example, it is not easy to define what is a representative form of lexical variants.
In your example, the official name of this company will be あおい電子工業株式会社, like Microsoft Corporation and Apple Inc, not あおい電子工業.
Another problem is that lexical variants can be formed in various ways including acronym (e.g., GM for General Motors Company) and abbreviations (e.g., MS for Microsoft Corporation).
Normalization of such variants are tricky since they are very ambiguous.
In many case, it needs sentence/document level information for accurate normalization.

**Comment by neologd** [comment]
Hi gary816-san. Thank you for your issue.
And thank you Cho-san. I think your comment is correct.

This issue include a few questions.
I answer to these questions.

Q1. Why do I generate 5 variants of "株式会社"  ?
A1.
When should we normalize the lexical variants on target text data is very important?
I think we should normalize data before Morphological Analysis process, because vocabulary of a dictionary of MA is limited.
It's common sense of people who knows Natural Language Processing.

On the one hand, using a library to normalization process correctly at good timing is difficult for almost Japanese web engineers.
And implementing a text normalization process is unable for almost Japanese web engineers.

I unwillingly generate the variants of every words which are included in seed data.
I placed importance on coverage for variants of word.

Q2. Why didn't I generate basic "あおい電子工業" ?
A2. 
"あおい電子工業" is very easy case for auto generation process of dictionary.

The example of difficult case for auto generation process is "アマノ株式会社".

"アマノ" has word sense ambiguity. 
When "アマノ" is an abbreviated name of company name, a Part of speech information is "名詞,固有名詞,組織,_,_,_".
When "アマノ" is a one of variant of Japanese family name of "天野(amano)", a Part of speech information is "名詞,固有名詞,人名,姓,_,*".
And I should think about other use cases of "アマノ". 

I can't annotate a POS informations with above process of thinking for every company names.
If you want to use basic "あおい電子工業" right now, you should use an user dictionary of MeCab.

Q3. Is there a solution to cover "あおい電子工業" ?
A3. 
I will support not just an abbreviated name of famous company names but also many Named Entity on around mecab-ipadic-NEologd v0.0.5.
If "あおい電子工業" is famous abbreviated name of "あおい電子工業株式会社", "あおい電子工業" will record.

Q4. What do I think about to reduce the dictionary size ?
A4. 
To reduce dictionary size is very important.
But I recommend to forget about dictionary size with present state of NEologd.
Because I will add much more millions of words to our dictionary.
I think, mecab-ipadic-NEologd will be use N-GByte of RAM in a few years.

Q5. Is there a solution to reduce the dictionary size ?
A5.
At least after releasing the mecab-ipadic-NEologd v0.0.5, I will implement "--ignore_not_famous_variants" option and I will split the seed dictionary in two or more.
This option will be ease the dictionary size problem.

That's all.
These answers aren't only for a suffix of "株式会社" .

Thank you for your analysis for the entries of dictionary.
I continue to improve mecab-ipadic-NEologd as quickly as possible :)

I close this issue for the present.

**Comment by ghost** [comment]
priancho, neologd, thank you for the replies.

> At least after releasing the mecab-ipadic-NEologd v0.0.5, I will implement "--ignore_not_famous_variants" option and I will split the seed dictionary in two or more.
> This option will be ease the dictionary size problem.

Great.

> I will support not just an abbreviated name of famous company names but also many Named Entity on around mecab-ipadic-NEologd v0.0.5.
> If "あおい電子工業" is famous abbreviated name of "あおい電子工業株式会社", "あおい電子工業" will record.

Then "明星食品" will be recorded in future mecab-ipadic-NEologd. :-)
Current NEologd has only one entry for 明星食品:
- 明星食品株式会社,1288,1288,-4479,名詞,固有名詞,一般,_,_,*,明星食品株式会社,ミョウジョウショクヒン,ミョージョーショクヒン

Thanks.
