### ISSUE TITLE
Request for adding wikipedia data.

### ISSUE THREAD

**Issue by yazumoto** [neologd/mecab-ipadic-neologd#34]
Your neologd dictionary is very useful.

I want to put wikipedia title words to mecab dictionary.
Can you please add data to neologd?

**Comment by neologd** [comment]
Thank you for your suggestion 😊
However, we can't respond to this type of request because we provide dictionary data of NEologd with Apatch License  version 2.0.
We will keep to collect a wide range of words quickly.
If you are managing a comprehensive word list that is given a "reading pseudonym" of a particular genre, we can consider including that list.
I am glad if you use it in the future✨
