### ISSUE TITLE
数値系が固有名詞になっている

### ISSUE THREAD

**Issue by m-takata** [neologd/mecab-ipadic-neologd#42]
$100,1288,1288,7806,名詞,固有名詞,一般,*,*,*,$100,ヒャクドル,ヒャクドル
昭和10年,1288,1288,6518,名詞,固有名詞,一般,*,*,*,昭和10年,ショウワジュウネン,ショーワジュウネン
10 years,1288,1288,4569,名詞,固有名詞,一般,*,*,*,10 years,テンイヤーズ,テンイヤーズ

などの数値系の辞書の品詞が、固有名詞になっているが、固有名詞ではないのではないでしょうか？
一般などの品詞に変えられないでしょうか？

**Comment by neologd** [comment]
Thank you very much for pointing out 👍

In conclusion, we have no motivation to change.

NEologd treats pairs of a numerals and units as proper nouns when generating dictionary entries.
I will explain two reasons for that.

First, numerical representation is a noun phrase to be extracted by techniques such as Named Entity Extraction.
Typical examples of numeric representations are dates and times.
And Named Entity means a proper noun.

Next, an amount(or size, length and so on) represented by a meaning of a pair of a numeral and a unit is not affected by the context in most cases.
I think that a noun phrase in which an entity to be expressed becomes unique can be treated as a proper noun.

At least I thought that the entries you cited as an example met the reasons above.

The reason for generating pairs of such numerals and units is because we want to give attribute information to frequent numerical representation.
For example, it is correct reading pseudonym.

That's all.

If there is any problem that everyone is troubled by this correspondence, please report it by all means.
