### ISSUE TITLE
Failed to build lucene-kuromoji because mecab-user-dict-seed.20180920.csv contain invalid format.

### ISSUE THREAD

**Issue by dAu6jARL** [neologd/mecab-ipadic-neologd#48]
mecab-user-dict-seed.20180920.csv contains invalid CSV format as follows.
### line 2236780:
`放虫,1283,1283,6095,名詞,サ変接続,**,*,*,放虫,ホウチュウ,ホーチュー,[unknown:_:17793	17615	6095]`
### line 2473240:
`死着,1283,1283,6095,名詞,サ変接続,**,*,*, 死着,シチャク,シチャク,[unknown:_:13429	13295	6095]`

**Comment by neologd** [comment]
Sorry for this error.
This error will correct by releasing new data(mecab-user-dict-seed.20180927.csv) on a few hours later.

This error was caused by new process to generate a dictionary resource.
We forgot to add a process to testing the output data from this new process.
And we added the process to testing it.

**Comment by dAu6jARL** [comment]
I checked success to build lucene-kuromoji by mecab-user-dict-seed.20180927.csv.
Thank you for your response and solution.
