### ISSUE TITLE
Failed to build lucene-kuromoji because mecab-user-dict-seed.20190930.csv contain invalid format.

### ISSUE THREAD

**Issue by dAu6jARL** [neologd/mecab-ipadic-neologd#63]
How have you been in a year?
mecab-user-dict-seed.20190930.csv contains invalid CSV format as follows.

line 1378761:
`マスストランディング,1288,1288,-141,名詞,固有名詞,一般,*,**,,マス・ストランディング,マスストランディング,マスストランディング`
`マスストランディング,1288,1288,-141,名詞,固有名詞,一般,*,*,*,マス・ストランディング,マスストランディング,マスストランディング`

**Comment by neologd** [comment]
Thank you for feedback,
Due to various our personal reasons, there was no time and the response was late.
We are sorry.
We sincerely apologize.
The update we made today has eliminated the same problem.
New and unknown words from the last month were also recorded.
We think we can update several times a week from this week, so please continue to use NEologd.
